/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.*;

/**
 *
 * @author ucwaz
 */


public class CropHealthView extends javax.swing.JFrame {

    public CropHealthView() {
        initComponents();
        setupStatusGroup();  
    }

    
    private void setupStatusGroup() {
       
        statusGroup.add(rbGood);
        statusGroup.add(rbWarning);
        statusGroup.add(rbCritical);
        rbGood.setSelected(true); // default
    }

    public javax.swing.JComboBox<?> getSeasonCombo() {
        return comboSeason; 
    }

    public javax.swing.JButton getBtnSave() {
        return btnSaveHarvest;   
    }

   
    public String getActualYieldText() {
        return txtActualYield.getText().trim(); 
    }


    public String getNotesText() {
        return txtNotes.getText();   
    }

    public javax.swing.JRadioButton getRbGood()     { return rbGood; }
    public javax.swing.JRadioButton getRbWarning()  { return rbWarning; }
    public javax.swing.JRadioButton getRbCritical() { return rbCritical; }

    public void showError(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Error", JOptionPane.ERROR_MESSAGE);
    }
    public void showInfo(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Info", JOptionPane.INFORMATION_MESSAGE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboSeason = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReportDate = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtActualYield = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();
        btnSaveHarvest = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        rbGood = new javax.swing.JRadioButton();
        rbWarning = new javax.swing.JRadioButton();
        rbCritical = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Record Crop Health");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 220, -1));

        jLabel2.setText("Actual Yield (kg)");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 110, 20));

        jLabel3.setText("Notes");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel4.setText("Report Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 100, 20));

        jLabel5.setText("Season");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 50, 20));

        jPanel1.add(comboSeason, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 270, -1));

        jScrollPane1.setViewportView(txtReportDate);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 220, -1));

        jScrollPane2.setViewportView(txtActualYield);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 220, -1));

        jLabel6.setText("Status");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        txtNotes.setColumns(20);
        txtNotes.setRows(5);
        jScrollPane3.setViewportView(txtNotes);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        btnSaveHarvest.setText("Save Harvest");
        jPanel1.add(btnSaveHarvest, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, -1));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 80, -1));

        rbGood.setText("Good");
        jPanel1.add(rbGood, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        rbWarning.setText("Warning");
        jPanel1.add(rbWarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        rbCritical.setText("Critical");
        rbCritical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCriticalActionPerformed(evt);
            }
        });
        jPanel1.add(rbCritical, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbCriticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCriticalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCriticalActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // Show confirmation dialog
        int choice = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to return to the Dashboard?\nAny unsaved changes will be lost.",
            "Confirm Exit",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
        
        // If user clicks Yes, close this window and return to dashboard
        if (choice == JOptionPane.YES_OPTION) {
            this.dispose();
            // The original dashboard should still be open in the background
        }
        // If user clicks No, do nothing - stay on this page
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CropHealthView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CropHealthView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CropHealthView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CropHealthView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CropHealthView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSaveHarvest;
    private javax.swing.JComboBox<String> comboSeason;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rbCritical;
    private javax.swing.JRadioButton rbGood;
    private javax.swing.JRadioButton rbWarning;
    private javax.swing.ButtonGroup statusGroup;
    private javax.swing.JTextPane txtActualYield;
    private javax.swing.JTextArea txtNotes;
    private javax.swing.JTextPane txtReportDate;
    // End of variables declaration//GEN-END:variables
}