/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import dao.DashboardDao;
import javax.swing.JLabel;
import javax.swing.*;


/**
 *
 * @author ucwaz
 */
public class DashboardView extends javax.swing.JFrame {
    private JLabel lblMessage;
    /**
     * Creates new form Dashboard
     */
    public DashboardView() {
        initComponents();
    }
    
    // ===== KPI setters called by the Controller =====
    public void setExpectedYield(double v) {
        lblExpectedYield.setText(String.format("%,.0f kg", v)); 
    }

    public void setActualYield(double v) {
        lblActualYield.setText(String.format("%,.0f kg", v));   
    }

    public void setAvailableHarvest(double v) {
        lblAvailableHarvest.setText(String.format("%,.0f kg", v)); 
    }

    // ===== Button getters so controller can add listeners =====
    public javax.swing.JButton getBtnAddSeasons() {return btnAddSeason;}
    public javax.swing.JButton getBtnRecordHarvest() {return btnRecordHarvest;}
    public javax.swing.JButton getBtnHealthReport() {return btnHealthReport;}
    public javax.swing.JButton getBtnBuyerDemands() {return btnBuyerDemands;}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAddSeason = new javax.swing.JButton();
        btnRecordHarvest = new javax.swing.JButton();
        btnHealthReport = new javax.swing.JButton();
        btnBuyerDemands = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSaveSeason = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblAvailableHarvest = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        lblExpectedYield = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        lblActualYield = new javax.swing.JTextPane();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Dashboard");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddSeason.setText("Add Seasons");
        jPanel1.add(btnAddSeason, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        btnRecordHarvest.setText("Record Harvest");
        jPanel1.add(btnRecordHarvest, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        btnHealthReport.setText("Health Report");
        jPanel1.add(btnHealthReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        btnBuyerDemands.setText("Buyer Demands");
        jPanel1.add(btnBuyerDemands, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 570, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 570, 10));

        jLabel2.setText("Active Crop Seaason");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Season", "Field", "Crop", "Farmer", "Start", "End", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 540, 150));

        btnSaveSeason.setText("Save Season");
        btnSaveSeason.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveSeasonActionPerformed(evt);
            }
        });
        jPanel1.add(btnSaveSeason, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Dashboard");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Available Harvest");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 120, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Expected Yield:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 100, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Actual Yield");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 100, -1));

        jScrollPane2.setViewportView(lblAvailableHarvest);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 130, -1));

        jScrollPane3.setViewportView(lblExpectedYield);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 150, -1));

        jScrollPane4.setViewportView(lblActualYield);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 150, -1));

        btnLogout.setText("Logout");
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 80, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveSeasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveSeasonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveSeasonActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // Show confirmation dialog
        int choice = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to logout?",
            "Confirm Logout",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );
        
        // If user clicks Yes, logout
        if (choice == JOptionPane.YES_OPTION) {
            // Close the dashboard
            this.dispose();
            
            // Open the login window
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new LoginView().setVisible(true);
                }
            });
        }
        // If user clicks No, do nothing - stay on dashboard
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSeason;
    private javax.swing.JButton btnBuyerDemands;
    private javax.swing.JButton btnHealthReport;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRecordHarvest;
    private javax.swing.JButton btnSaveSeason;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane lblActualYield;
    private javax.swing.JTextPane lblAvailableHarvest;
    private javax.swing.JTextPane lblExpectedYield;
    // End of variables declaration//GEN-END:variables

}
