/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import model.ComboItem;
import controller.HarvestController;
import javax.swing.*;
import java.util.List;

/**
 *
 * @author ucwaz
 */
public class HarvestView extends javax.swing.JFrame {

    /**
     * Creates new form Sales_And_Distribution
     */
    public HarvestView() {
        initComponents();
        
        // Initialize controller to load seasons
        new HarvestController(this);
        
        // Button group for quality grade checkboxes
        ButtonGroup qualityGroup = new ButtonGroup();
        qualityGroup.add(GoodCheckBox);
        qualityGroup.add(WarningCheckBox);
        qualityGroup.add(CriticalCheckBox);
    }

    // =========================
    // PUBLIC VIEW METHODS
    // =========================

    public void setSeasonItems(List<ComboItem> items) {
        cmbSeason.removeAllItems();
        for (ComboItem item : items) {
            cmbSeason.addItem(item);
        }
    }

    public ComboItem getSelectedSeason() {
        return (ComboItem) cmbSeason.getSelectedItem();
    }

    public String getHarvestDate() {
        return txtReportDate.getText().trim();
    }

    public String getYield() {
        return txtYield.getText().trim();
    }

    public String getNotes() {
        return txtNotes1.getText().trim();
    }

    public String getQualityGrade() {
        if (GoodCheckBox.isSelected()) return "Good";
        if (WarningCheckBox.isSelected()) return "Warning";
        if (CriticalCheckBox.isSelected()) return "Critical";
        return null;
    }
    
    public void clearForm() {
        if (cmbSeason.getItemCount() > 0) cmbSeason.setSelectedIndex(0);
        txtReportDate.setText("");
        txtYield.setText("");
        txtNotes1.setText("");
        GoodCheckBox.setSelected(false);
        WarningCheckBox.setSelected(false);
        CriticalCheckBox.setSelected(false);
    }
    
    public void showSuccess(String message) {
        JOptionPane.showMessageDialog(this, message, "Success", JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void showError(String message) {
        JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();
        btnHarvest = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cmbSeason = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReportDate = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtYield = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        GoodCheckBox = new javax.swing.JCheckBox();
        WarningCheckBox = new javax.swing.JCheckBox();
        CriticalCheckBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtNotes1 = new javax.swing.JTextArea();
        btnSaveHarvest = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        jLabel3.setText("Notes");

        txtNotes.setColumns(20);
        txtNotes.setRows(5);
        jScrollPane3.setViewportView(txtNotes);

        btnHarvest.setText("Save Harvest");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.add(cmbSeason, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 200, -1));

        jLabel5.setText("Season");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel4.setText("Harvest Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 120, 20));

        jScrollPane1.setViewportView(txtReportDate);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 150, -1));

        jScrollPane2.setViewportView(txtYield);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 150, -1));

        jLabel2.setText("Actual Yield (kg)");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 110, 20));

        jLabel6.setText("Quality Grade");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        GoodCheckBox.setText("Good");
        GoodCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoodCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(GoodCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        WarningCheckBox.setText("Warning");
        WarningCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WarningCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(WarningCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        CriticalCheckBox.setText("Critical");
        CriticalCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriticalCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(CriticalCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Harvest & Supply Recording");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel7.setText("Notes");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        txtNotes1.setColumns(20);
        txtNotes1.setRows(5);
        jScrollPane4.setViewportView(txtNotes1);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        btnSaveHarvest.setText("Save Harvest");
        btnSaveHarvest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveHarvestActionPerformed(evt);
            }
        });
        jPanel1.add(btnSaveHarvest, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, -1, -1));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 80, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WarningCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WarningCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WarningCheckBoxActionPerformed

    private void GoodCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoodCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GoodCheckBoxActionPerformed

    private void CriticalCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriticalCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CriticalCheckBoxActionPerformed

    private void btnSaveHarvestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveHarvestActionPerformed
        // Validate inputs
        ComboItem selectedSeason = getSelectedSeason();
        if (selectedSeason == null || selectedSeason.getId() == 0) {
            showError("Please select a season.");
            return;
        }
        
        String harvestDate = getHarvestDate();
        if (harvestDate.isEmpty()) {
            showError("Please enter harvest date.");
            return;
        }
        
        String yield = getYield();
        if (yield.isEmpty()) {
            showError("Please enter actual yield.");
            return;
        }
        
        String qualityGrade = getQualityGrade();
        if (qualityGrade == null) {
            showError("Please select a quality grade.");
            return;
        }
        
        // TODO: Save harvest data to database
        // For now, just show success message
        String message = String.format(
            "Harvest Record Saved:\n" +
            "Season: %s\n" +
            "Date: %s\n" +
            "Yield: %s kg\n" +
            "Quality: %s\n" +
            "Notes: %s",
            selectedSeason.getLabel(),
            harvestDate,
            yield,
            qualityGrade,
            getNotes()
        );
        
        showSuccess(message);
        clearForm();
    }//GEN-LAST:event_btnSaveHarvestActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // Show confirmation dialog
        int choice = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to return to the Dashboard?\nAny unsaved changes will be lost.",
            "Confirm Exit",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
        
        // If user clicks Yes, close this window and return to dashboard
        if (choice == JOptionPane.YES_OPTION) {
            this.dispose();
            // The original dashboard should still be open in the background
        }
        // If user clicks No, do nothing - stay on this page
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HarvestView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HarvestView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HarvestView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HarvestView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HarvestView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CriticalCheckBox;
    private javax.swing.JCheckBox GoodCheckBox;
    private javax.swing.JCheckBox WarningCheckBox;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHarvest;
    private javax.swing.JButton btnSaveHarvest;
    private javax.swing.JComboBox<ComboItem> cmbSeason;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea txtNotes;
    private javax.swing.JTextArea txtNotes1;
    private javax.swing.JTextPane txtReportDate;
    private javax.swing.JTextPane txtYield;
    // End of variables declaration//GEN-END:variables
}